//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaLibreriaImagina.wsImaginaEnvio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsImaginaEnvio.ImaginaEnvioSoap")]
    public interface ImaginaEnvioSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GenerateShipmentsResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerateShipments", ReplyAction="*")]
        SistemaLibreriaImagina.wsImaginaEnvio.GenerateShipmentsResponse GenerateShipments(SistemaLibreriaImagina.wsImaginaEnvio.GenerateShipmentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerateShipments", ReplyAction="*")]
        System.Threading.Tasks.Task<SistemaLibreriaImagina.wsImaginaEnvio.GenerateShipmentsResponse> GenerateShipmentsAsync(SistemaLibreriaImagina.wsImaginaEnvio.GenerateShipmentsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateShipmentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateShipments", Namespace="http://tempuri.org/", Order=0)]
        public SistemaLibreriaImagina.wsImaginaEnvio.GenerateShipmentsRequestBody Body;
        
        public GenerateShipmentsRequest() {
        }
        
        public GenerateShipmentsRequest(SistemaLibreriaImagina.wsImaginaEnvio.GenerateShipmentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenerateShipmentsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime fecha_envio;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long direccion_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long pedido_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long repartidor_id;
        
        public GenerateShipmentsRequestBody() {
        }
        
        public GenerateShipmentsRequestBody(System.DateTime fecha_envio, long direccion_id, long pedido_id, long repartidor_id) {
            this.fecha_envio = fecha_envio;
            this.direccion_id = direccion_id;
            this.pedido_id = pedido_id;
            this.repartidor_id = repartidor_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateShipmentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateShipmentsResponse", Namespace="http://tempuri.org/", Order=0)]
        public SistemaLibreriaImagina.wsImaginaEnvio.GenerateShipmentsResponseBody Body;
        
        public GenerateShipmentsResponse() {
        }
        
        public GenerateShipmentsResponse(SistemaLibreriaImagina.wsImaginaEnvio.GenerateShipmentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenerateShipmentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GenerateShipmentsResult;
        
        public GenerateShipmentsResponseBody() {
        }
        
        public GenerateShipmentsResponseBody(string GenerateShipmentsResult) {
            this.GenerateShipmentsResult = GenerateShipmentsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ImaginaEnvioSoapChannel : SistemaLibreriaImagina.wsImaginaEnvio.ImaginaEnvioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImaginaEnvioSoapClient : System.ServiceModel.ClientBase<SistemaLibreriaImagina.wsImaginaEnvio.ImaginaEnvioSoap>, SistemaLibreriaImagina.wsImaginaEnvio.ImaginaEnvioSoap {
        
        public ImaginaEnvioSoapClient() {
        }
        
        public ImaginaEnvioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImaginaEnvioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImaginaEnvioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImaginaEnvioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaLibreriaImagina.wsImaginaEnvio.GenerateShipmentsResponse SistemaLibreriaImagina.wsImaginaEnvio.ImaginaEnvioSoap.GenerateShipments(SistemaLibreriaImagina.wsImaginaEnvio.GenerateShipmentsRequest request) {
            return base.Channel.GenerateShipments(request);
        }
        
        public string GenerateShipments(System.DateTime fecha_envio, long direccion_id, long pedido_id, long repartidor_id) {
            SistemaLibreriaImagina.wsImaginaEnvio.GenerateShipmentsRequest inValue = new SistemaLibreriaImagina.wsImaginaEnvio.GenerateShipmentsRequest();
            inValue.Body = new SistemaLibreriaImagina.wsImaginaEnvio.GenerateShipmentsRequestBody();
            inValue.Body.fecha_envio = fecha_envio;
            inValue.Body.direccion_id = direccion_id;
            inValue.Body.pedido_id = pedido_id;
            inValue.Body.repartidor_id = repartidor_id;
            SistemaLibreriaImagina.wsImaginaEnvio.GenerateShipmentsResponse retVal = ((SistemaLibreriaImagina.wsImaginaEnvio.ImaginaEnvioSoap)(this)).GenerateShipments(inValue);
            return retVal.Body.GenerateShipmentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaLibreriaImagina.wsImaginaEnvio.GenerateShipmentsResponse> SistemaLibreriaImagina.wsImaginaEnvio.ImaginaEnvioSoap.GenerateShipmentsAsync(SistemaLibreriaImagina.wsImaginaEnvio.GenerateShipmentsRequest request) {
            return base.Channel.GenerateShipmentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaLibreriaImagina.wsImaginaEnvio.GenerateShipmentsResponse> GenerateShipmentsAsync(System.DateTime fecha_envio, long direccion_id, long pedido_id, long repartidor_id) {
            SistemaLibreriaImagina.wsImaginaEnvio.GenerateShipmentsRequest inValue = new SistemaLibreriaImagina.wsImaginaEnvio.GenerateShipmentsRequest();
            inValue.Body = new SistemaLibreriaImagina.wsImaginaEnvio.GenerateShipmentsRequestBody();
            inValue.Body.fecha_envio = fecha_envio;
            inValue.Body.direccion_id = direccion_id;
            inValue.Body.pedido_id = pedido_id;
            inValue.Body.repartidor_id = repartidor_id;
            return ((SistemaLibreriaImagina.wsImaginaEnvio.ImaginaEnvioSoap)(this)).GenerateShipmentsAsync(inValue);
        }
    }
}
