//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaLibreriaImagina.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMIN_INTERFACE_THEME
    {
        public long ID { get; set; }
        public string NAME { get; set; }
        public bool ACTIVE { get; set; }
        public string TITLE { get; set; }
        public bool TITLE_VISIBLE { get; set; }
        public string LOGO { get; set; }
        public bool LOGO_VISIBLE { get; set; }
        public string CSS_HEADER_BACKGROUND_COLOR { get; set; }
        public string TITLE_COLOR { get; set; }
        public string CSS_HEADER_TEXT_COLOR { get; set; }
        public string CSS_HEADER_LINK_COLOR { get; set; }
        public string CSS_HEADER_LINK_HOVER_COLOR { get; set; }
        public string CSS_MODULE_BACKGROUND_COLOR { get; set; }
        public string CSS_MODULE_TEXT_COLOR { get; set; }
        public string CSS_MODULE_LINK_COLOR { get; set; }
        public string CSS_MODULE_LINK_HOVER_COLOR { get; set; }
        public bool CSS_MODULE_ROUNDED_CORNERS { get; set; }
        public string CSS_GENERIC_LINK_COLOR { get; set; }
        public string CSS_GENERIC_LINK_HOVER_COLOR { get; set; }
        public string CSS_SAVE_BUTTON_BACKGROUND99E4 { get; set; }
        public string CSS_SAVE_BUTTON_BACKGROUND20F4 { get; set; }
        public string CSS_SAVE_BUTTON_TEXT_COLOR { get; set; }
        public string CSS_DELETE_BUTTON_BACKGROUE0B7 { get; set; }
        public string CSS_DELETE_BUTTON_BACKGROUA080 { get; set; }
        public string CSS_DELETE_BUTTON_TEXT_COLOR { get; set; }
        public bool LIST_FILTER_DROPDOWN { get; set; }
        public bool RELATED_MODAL_ACTIVE { get; set; }
        public string RELATED_MODAL_BACKGROUND_COLOR { get; set; }
        public bool RELATED_MODAL_ROUNDED_CORNERS { get; set; }
        public string LOGO_COLOR { get; set; }
        public bool RECENT_ACTIONS_VISIBLE { get; set; }
        public string FAVICON { get; set; }
        public string RELATED_MODAL_BACKGROUND_OE111 { get; set; }
        public string ENV_NAME { get; set; }
        public Nullable<bool> ENV_VISIBLE_IN_HEADER { get; set; }
        public string ENV_COLOR { get; set; }
        public bool ENV_VISIBLE_IN_FAVICON { get; set; }
        public bool RELATED_MODAL_CLOSE_BUTTON3B73 { get; set; }
        public bool LANGUAGE_CHOOSER_ACTIVE { get; set; }
        public string LANGUAGE_CHOOSER_DISPLAY { get; set; }
        public bool LIST_FILTER_STICKY { get; set; }
        public bool FORM_PAGINATION_STICKY { get; set; }
        public bool FORM_SUBMIT_STICKY { get; set; }
        public string CSS_MODULE_BACKGROUND_SELE1A15 { get; set; }
        public string CSS_MODULE_LINK_SELECTED_COLOR { get; set; }
        public long LOGO_MAX_HEIGHT { get; set; }
        public long LOGO_MAX_WIDTH { get; set; }
        public bool FOLDABLE_APPS { get; set; }
        public string LANGUAGE_CHOOSER_CONTROL { get; set; }
        public bool LIST_FILTER_HIGHLIGHT { get; set; }
        public bool LIST_FILTER_REMOVAL_LINKS { get; set; }
        public bool SHOW_FIELDSETS_AS_TABS { get; set; }
        public bool SHOW_INLINES_AS_TABS { get; set; }
        public string CSS_GENERIC_LINK_ACTIVE_COLOR { get; set; }
    }
}
