//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaLibreriaImagina.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_CARRITO
    {
        public long ID { get; set; }
        public long CANTIDAD { get; set; }
        public decimal PRECIO_TOTAL { get; set; }
        public long CARRITO_ID { get; set; }
        public long LIBRO_ID { get; set; }
    
        public virtual CARRITO CARRITO { get; set; }
        public virtual LIBRO LIBRO { get; set; }
    }
}
